apiVersion: v1
kind: Pod
metadata:
  name: doscontenedores
spec:
  containers:
    - name: cont1
      image: python:3.6-alpine
      command:
        [
          "sh",
          "-c",
          'echo "contenedor 1" > index.html && python -m http.server 8082',
        ]
    - name: cont2
      image: python:3.6-alpine
      command:
        [
          "sh",
          "-c",
          'echo "contenedor 2" > index.html && python -m http.server 8082',
        ]
